### ISSUE TITLE
"widget_update_callback" action is not working

### ISSUE THREAD

**Issue by suganyaselvakumar** [siteorigin/docs#24]
Siteorigin is not happy for the following issues,

1.negative margin in measurement field:
    it's work fine in css, but for (e.x) I gave -40(negative) and save the value, the field will show only  40 (positive) value.

2.`in_widget_form` action is working good ,but "widget_update_callback" action is not working when rendering to update the widgets value.

**Comment by AlexGStapleton** [comment]
1. This, at the moment, is intentional as this feature is mostly used in situations where negative values aren't allowed (borders and padding for examples). We'll look to a parameter that makes this optional in the future.

2. We've logged this as an issue, although it's directly tied to a third party plugin. siteorigin/siteorigin-panels#518
