### ISSUE TITLE
Extending Existing Widgets

### ISSUE THREAD

**Issue by dillonbailey** [siteorigin/docs#54]
More of a documentation clarification request for https://github.com/siteorigin/docs/blob/develop/widgets-bundle/getting-started/extending-existing-widgets.md

The snippet for changing the template file could use some clarification around the `if` statement that allows the filename to get replaced. In my use case `$instance['design']` was empty so I removed this check and everything seems to be working as expected. 

```
function mytheme_button_template_file( $filename, $instance, $widget ){
	if( !empty($instance['design']['theme']) && $instance['design']['theme'] == 'test' ) { // What's the purpose of this line?
		// This option works for plugins
		$filename = plugin_dir_path( __FILE__ ) . 'tpl/button.php';
		
		// And this one for themes
		$filename = get_stylesheet_directory() . '/tpl/button.php'; 
	}
	return $filename;
}
add_filter( 'siteorigin_widgets_template_file_sow-button', 'mytheme_button_template_file', 10, 3 );
```

**Comment by AlexGStapleton** [comment]
Okay so `$instance['design']['theme']` is the variable of the theme drop down for the button widget. Basically, if the user selects the atom theme - `$instance['design']['theme']` will equal `atom`. It's a way for a user to select what theme they actually want to use - it extends the existing theme functionality rather than replacing it.

Not using an `if` clause will prevent the button theme drop down from working and lock the theme to your custom theme.

I'm going to make a few modifications to the doc.

**Comment by dillonbailey** [comment]
@AlexGStapleton awesome mate and cheers for the speedy reply!
